//фаил для пользователя, ему так легче заменить слайды, не нужно ковырятся в коде
var sliderText = {
    h2_0:'Unique and Modern Design',
    h1_0: "Portfolio PSD Template",
    p_0: 'Nam liber tempor cum soluta nobis eleifend option congue nihil imperdiet doming id quod mazim placerat facer possim assum.',
    a_0: 'GET STARTED',
    a_00: 'http://ya.ru',
    h2_1: 'Слайд 2',
    h1_1: "Заголовок слада 2",
    p_1: 'Текст ко второму сладу',
    a_1: 'Кнопка два',
    a_11: 'http://goole.ru',
    h2_2:'Слайд 3',
    h1_2: "Заголовок слада 3",
    p_2: 'Текст к третьему сладу',
    a_2: 'кнопка три',
    a_22: 'http://ya.ru',
    h2_3:'Слайд 4',
    h1_3: "Заголовок слада 4",
    p_3: 'Текст к четвертому сладу',
    a_3: 'кнопка 4',
    a_33: 'http://ya.ru',
};
